### ISSUE TITLE
how could i use gpio with c++?

### ISSUE THREAD

**Issue by xuguosheng110** [NVIDIA/jetson-gpio#102]
**Please don't submit questions**
Please use this form to report specific bugs in Jetson.GPIO. All general questions or support requests should be directed at NVIDIA's forums; see:
https://developer.nvidia.com/embedded/community/support-resources

Please delete this section from your bug report.

**Describe the bug**
A clear and concise description of what the bug is, including
- Which version of Jetson.GPIO you are using.
- Which version of L4T (not JetPack) you are using.
- Which Jetson board you are using.

**To Reproduce**
1. Connect  button/wire/LED/... XXX to the board
2. Configure pin ... to input/output/...
3. Execute API ...

**Expected behavior**

**Additional context**

**Comment by anhmiuhv** [comment]
There is a third party tool called https://github.com/pjueon/JetsonGPIO that use C++

You can also use https://www.ics.com/blog/gpio-programming-exploring-libgpiod-library and https://libgpiod.readthedocs.io/en/latest/group__gpiod__cxx.html#details to program GPIO directly using libgpiod C++ binding
