### ISSUE TITLE
Multi-Pin

### ISSUE THREAD

**Issue by Satge96** [NVIDIA/jetson-gpio#108]
I wanted to ask how it would be possible to change multiple pins truly simultaneously. Can I do that in Python?

**Comment by anhmiuhv** [comment]
Is this something you want to do? https://stackoverflow.com/questions/11523918/start-a-function-at-given-time

However, the GPIO bank in the Jetson would process the request sequentially due to hardware limitation. there will be a very small time delay between the pins.

**Comment by Satge96** [comment]
The time when the Pins are toggled is not relevant to me as long as it's at the same time. Would you have an idea or even an example for that?

**Comment by anhmiuhv** [comment]
[def output(channels, values):](https://github.com/NVIDIA/jetson-gpio/blob/2b6da70499175f97a581423c15b20f34d4dd43b4/lib/python/Jetson/GPIO/gpio.py#L407)


output can take a list of GPIO and a list of corresponding values.
