### ISSUE TITLE
Unable to use pins 3, 5 as GPIO

### ISSUE THREAD

**Issue by KopecekCVUT** [NVIDIA/jetson-gpio#109]
Using the latest version of your library, I'm not able to set I2C pins as GPIOs, code raises exception "Channel x is invalid." But in datasheet for board Jetson Orin Nano, I have read that all pins can be configured as GPIO.

**Comment by anhmiuhv** [comment]
Hi This library is designed to be compatible with the PIN layout of the Raspberry Pi so some pins are unavailable for used. YOu can use libgpiod to control unavailable pin. Also remember to set the pinmux to the appropriate value.
