### ISSUE TITLE
HI, do you have a C code for GPIO control

### ISSUE THREAD

**Issue by gaosiy** [NVIDIA/jetson-gpio#11]
HI, do you have a C code for GPIO control

**Comment by swarren** [comment]
Sorry, no. This library is Python only.

The following page lists the best support resources for general questions:
https://developer.nvidia.com/embedded/community/support-resources

**Comment by gaosiy** [comment]
https://github.com/gaosiy/JetsonXavierGPIO
I have wrote one for someone need C
