### ISSUE TITLE
Remove Python 2 requirement

### ISSUE THREAD

**Issue by paulober** [NVIDIA/jetson-gpio#111]
**Please don't submit questions**
Please use this form to report specific bugs in Jetson.GPIO. All general questions or support requests should be directed at NVIDIA's forums; see:
https://developer.nvidia.com/embedded/community/support-resources

Please delete this section from your bug report.

**Describe the bug**
A clear and concise description of what the bug is, including
- All newest version as of 28.07.2024
- On Jetson Orin NX 16GB

**To Reproduce**
1. Setup new device

**Expected behavior**
The only package dependent on python2 is this module. As python2 is way out of it's service period and contains many security vulnerabilities it would be great if this module could dump it from the dependencies list, so L4T can be Python2 less setup.

**Additional context**

**Comment by anhmiuhv** [comment]
I think this module has separate packages for python3 and python2. So all you need to do is uninstall the package for python2

**Comment by paulober** [comment]
> I think this module has separate packages for python3 and python2. So all you need to do is uninstall the package for python2

That would be great but uninstalling python2 will show following packages to be removed: `python-jetson-gpio python2 python2.7`

**Comment by anhmiuhv** [comment]
The OS does not rely on any packages from Jetson GPIO to run

**Comment by paulober** [comment]
> The OS does not rely on any packages from Jetson GPIO to run
ok, thanks.
