### ISSUE TITLE
Confusing test code 

### ISSUE THREAD

**Issue by evybs** [NVIDIA/jetson-gpio#27]
Hi,

I reviewed the code of test_all_apis.py script, and I belive in test_setup_one_out_no_init function it should be GPIO.OUT (rather then GPIO.IN)

https://github.com/NVIDIA/jetson-gpio/blob/34f0f46b6210c4998c4a6e54992c4883ba7fafc5/samples/test_all_apis.py#L142

The tests probably passed anyway due to the fact that and digital output pin is also input pin.

**Comment by swarren** [comment]
Thanks for reviewing the test code! This was indeed a bug, and I've pushed a fix.
