### ISSUE TITLE
cannot find devices

### ISSUE THREAD

**Issue by Q-Z-one** [NVIDIA/jetson-gpio#3]
I do everything as the readme file say, but the terminal returns the following err
`No such file or directory: '/sys/devices/3160000.i2c/i2c-0/0-0074/gpio`

I reboot jetson but it seems that doesn't work, btw, I have run the sample successfully on the same jetson just yesterday.

**Comment by swarren** [comment]
Please obtain support from the web forum linked at https://developer.nvidia.com/embedded/community/support-resources.

> btw, I have run the sample successfully on the same jetson just yesterday.

It sounds like there's no issue with Jetson.GPIO itself, then.

**Comment by swarren** [comment]
@Q-Z-one did you resolve this issue?

**Comment by swarren** [comment]
I assume this is not an issue in the Jetson.GPIO since it worked once. Hence, closing. If this issue still persists, and it's an issue with the library itself, feel free to re-open this bug.
