### ISSUE TITLE
support for orbitty board 

### ISSUE THREAD

**Issue by yogeshwar607** [NVIDIA/jetson-gpio#30]
I am trying to use this library with orbitty board  on jetson tx2 , getting below error , any recommendations on how to get it working ?

![image](https://user-images.githubusercontent.com/10059011/69992273-559b0f80-156f-11ea-94d4-e5c61f5340bc.png)

**Comment by swarren** [comment]
The library only supports the baseboards in the NVIDIA developer kits. Third party hardware is not supported. Sorry.
