### ISSUE TITLE
need mount /sys/class/gpio in k8s

### ISSUE THREAD

**Issue by ryanaltair** [NVIDIA/jetson-gpio#34]
**Describe the bug**
Jetson.GPIO failed work in kubernetes but docker.
Have to apparently mount /sys/class/gpio into pods

**Comment by swarren** [comment]
This bug doesn't sound related to Jetson.GPIO, but rather is simply a misconfiguration on the part of the Kubernetes container. What bug do you believe existing in Jetson.GPIO itself? Jetson.GPIO can't know anything about the containers that a user creates, nor does can it influence their configuration as far as I know.

**Comment by ryanaltair** [comment]
Ye, that's due to misconfig of kubernetes. Mount /sys into Kubernetes pod as /sys then everything works. Thanks anyway.
