### ISSUE TITLE
No "99-gpio. rules file in the GPIO directory 

### ISSUE THREAD

**Issue by TCIII** [NVIDIA/jetson-gpio#36]
**Please don't submit questions**
Please use this form to report specific bugs in Jetson.GPIO. All general questions or support requests should be directed at NVIDIA's forums; see:
https://developer.nvidia.com/embedded/community/support-resources

Please delete this section from your bug report.

**Describe the bug**
A clear and concise description of what the bug is, including
- Which version of Jetson.GPIO you are using.
- Which version of L4T (not JetPack) you are using.
- Which Jetson board you are using.

**To Reproduce**
1. Connect  button/wire/LED/... XXX to the board
2. Configure pin ... to input/output/...
3. Execute API ...

**Expected behavior**

**Additional context**

**Comment by TCIII** [comment]
Sorry, my issue is with JetPack and not L4T.

**Comment by jorgemia** [comment]
@TCIII I can't find a rules file either. Were you able to fix it?

**Comment by TCIII** [comment]
@jorgemia,

I ignored the warning and all was well.

Regards,
TCIII
