### ISSUE TITLE
Event triggered twice despite high debounce time

### ISSUE THREAD

**Issue by tasiogr** [NVIDIA/jetson-gpio#40]
I'm playing with the button_interrupt.py sample and I'm getting some strange behavior.

I'm running Jetson.GPIO 2.0.8 on L4T # R32 (release), REVISION: 4.2, GCID: 20074772, BOARD: t210ref. Jetson Nano Development Kit B01.

I have connected a button to the J41 pin 31 (which is supposed to be by default configured as pull up, correct me if I'm wrong here). The pin is configured as input as per the sample.

With the original sample, I get the event triggered twice. When I use a not-so-low debounce time (even up to a second), I get an event triggered twice. If I raise the debounce time up to a point where I don't get the event repeated (e.g.: two seconds), I get the event triggered once, but the button stops responding and the python program will need two Ctrl+C until it gets the keyboard interrupt. I guess this indicates the thread gets stuck somewhere, looks like waiting for some mutex unlock.

Here's the traceback after the double Ctrl+C:

```
Starting demo now! Press CTRL+C to exit
Blink LED 2
^C^CTraceback (most recent call last):
  File "./test_button.py", line 57, in main
    time.sleep(2)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test_button.py", line 62, in <module>
    main()
  File "./test_button.py", line 59, in main
    GPIO.cleanup()  # cleanup all GPIOs
  File "/usr/local/lib/python3.7/dist-packages/Jetson/GPIO/gpio.py", line 396, in cleanup
    _cleanup_all()
  File "/usr/local/lib/python3.7/dist-packages/Jetson/GPIO/gpio.py", line 293, in _cleanup_all
    _cleanup_one(ch_info)
  File "/usr/local/lib/python3.7/dist-packages/Jetson/GPIO/gpio.py", line 283, in _cleanup_one
    event.event_cleanup(ch_info.gpio)
  File "/usr/local/lib/python3.7/dist-packages/Jetson/GPIO/gpio_event.py", line 369, in event_cleanup
    remove_edge_detect(gpio)
  File "/usr/local/lib/python3.7/dist-packages/Jetson/GPIO/gpio_event.py", line 136, in remove_edge_detect
    _mutex.acquire()
KeyboardInterrupt
```

**Comment by swarren** [comment]
Thanks for the report. Unfortunately, this will have to wait a while, since I don't have physical access to any Jetson in order to wire up some input to test this. I should have connected some loopback wires before I left the office.

**Comment by Nisces** [comment]
I have the same problem, when set a bounce time(no matter what value), the program stops responding and need two Ctrl+C until it gets the keyboard interrupt.

**Comment by swarren** [comment]
I have pushed version 2.0.9 which should resolve the hang and double-CTRL-C-required issues.

A terminology note: the word "debounce" in the event API doesn't mean what you might typically think debounce means. It's implemented as a simple maximum-callback-rate, rather than the likely expected don't-notify-until-the-value-has-been-stable-for-x-ms. This behaviour matches the original RPi.GPIO library, which Jetson.GPIO emulates in order to ensure application compatibility.
