### ISSUE TITLE
Update for Jetson Xavier NX

### ISSUE THREAD

**Issue by aldrichg9** [NVIDIA/jetson-gpio#49]
I wonder if there is an updated version for the Xavier NX?

**Comment by swarren** [comment]
Jetson.GPIO already fully supports Jetson Xavier NX. There's no update available beyond what's already present in this repository or on PyPI.

Quoting from the original bug description before the edit:
> e.g. I want to use pin 445, but it is not listed in gpio_pin_data.py

Note that Jetson.GPIO deliberately only supports pins attached to the 40-pin GPIO expansion connector. I'm not sure what "pin 445" refers to; which device or connector is that pin part of? Thanks.

**Comment by aldrichg9** [comment]
![image](https://user-images.githubusercontent.com/25693009/106318271-4b3cda00-6235-11eb-90ba-9e26f1c8b27d.png)

**Comment by swarren** [comment]
That is Linux GPIO number 445. In turn, that's the following GPIO number for Jetson.GPIO:
* BOARD mode: 12 (from the pin number on the connector/header).
* BCM mode: 18.

**Comment by aldrichg9** [comment]
> That is Linux GPIO number 445. In turn, that's the following GPIO number for Jetson.GPIO:
> 
> * BOARD mode: 12 (from the pin number on the connector/header).
> * BCM mode: 18.

Thanks swarren for your replies.

**Comment by swarren** [comment]
@aldrichg9 I believe we can close this bug now? Thanks.

**Comment by aldrichg9** [comment]
> @aldrichg9 I believe we can close this bug now? Thanks.

Of course!  Thank you for your help.

**Comment by swarren** [comment]
Thanks.
