### ISSUE TITLE
Install nvidia jetson-gpio on docker container

### ISSUE THREAD

**Issue by MostafaRafea19** [NVIDIA/jetson-gpio#53]
Is there a dockerfile for installing nvidia jetson-gpio on docker
I tried to write the Dockerfile myself but when I import the library in my python file I get this error:
RuntimeError: The current user does not have permissions set to access the library functionalites. Please configure permissions or use the root user to run this

**Comment by MostafaRafea19** [comment]
@swarren 
@aaronp24 
@lukeyeager 
@AeroNotix

**Comment by anhmiuhv** [comment]
There is none that I am aware of. Maybe you can reference to this bug https://github.com/NVIDIA/jetson-gpio/issues/52

**Comment by anhmiuhv** [comment]
Is there anything else?

**Comment by anhmiuhv** [comment]
Closed as there is no response.
