### ISSUE TITLE
how to use 4 PWM with the library on Jetson Xavier NX?

### ISSUE THREAD

**Issue by AndreV84** [NVIDIA/jetson-gpio#55]
it doesn't seem to support NX fan PWM  pin-230/GPIO14 that is out of the  40 pin  GPIO header

**Comment by AndreV84** [comment]
reference thread https://forums.developer.nvidia.com/t/how-to-use-pwm-on-xavier-nx/163863/18?u=andrey1984

**Comment by anhmiuhv** [comment]
You can use sysfs like the engineer said. jetson-gpio use sysfs internally

**Comment by AndreV84** [comment]
thank you for following up!
