### ISSUE TITLE
incorrect RAM size in JETSON_INFO

### ISSUE THREAD

**Issue by pjueon** [NVIDIA/jetson-gpio#64]
**Describe the bug**
I'm using Jetson Nano 2GB model and Jetson.GPIO v.2.0.17.
When I run `print(GPIO.JETSON_INFO)` in my code, 
I get this: 
```
{'P1_REVISION': 1, 'RAM': '4096M', 'REVISION': 'Unknown', 'TYPE': 'Jetson Nano', 'MANUFACTURER': 'NVIDIA', 'PROCESSOR': 'ARM A57'}
```
But I think the RAM should be **2048M** because I'm using 2GB model.
I know it's not a critical issue, but it would be nice to be fixed.

**To Reproduce**
run `print(GPIO.JETSON_INFO)` on Jetson Nano 2GB model.

**Expected behavior**
```
{'P1_REVISION': 1, 'RAM': '2048M', 'REVISION': 'Unknown', 'TYPE': 'Jetson Nano', 'MANUFACTURER': 'NVIDIA', 'PROCESSOR': 'ARM A57'}
```

**Comment by anhmiuhv** [comment]
There are a few variants of Jetson Nano. I will update with appropriate info
