### ISSUE TITLE
GPIO events are triggered on modbus writes

### ISSUE THREAD

**Issue by yassiezar** [NVIDIA/jetson-gpio#67]
**Bug description**
We have 4 GPIO buttons connected to a Jetson as inputs. We also have a modbus interface configured to send single bit packets over TCP using libmodbus. We set up the 4 GPIOs to use the interrupt event functionality similar to the [sample](https://github.com/NVIDIA/jetson-gpio/blob/master/samples/button_interrupt.py). However, when we send a packet over modbus to another subsystem, the GPIO events are triggered at random (e.g. sometimes 1, none or all of them).

We tested with the latest Jetson.GPIO as of now (2.0.17), using L4T R32.5.1 and [Aetina AX720 carrier board](https://www.aetina.com/products-detail.php?i=417).

**To reproduce**
Steps to reproduce the behaviour:
1. Connect GPIO buttons to pins 13, 15, 18, 22
2. Configure a modbus interface to write via TCP to address 10.10.0.2:502
3. Run script to set up GPIOs and their event callbacks (e.g. simple print statement)
4. Write modbus message to coil 0 with the [modbus_cli package](https://pypi.org/project/modbus-cli/) using the command `modbus 10.10.0.2:502 c@3=0` 

**Expected behavior**
The observed behaviour is that writing messages to this particular modbus address triggers GPIO events at random - sometimes 1, sometimes none, and other times all defined event callbacks. None of the other modbus writes have any effect. The expected behaviour is for modbus to not interact with the GPIOs and only respond to physical GPIO button presses.

**Comment by anhmiuhv** [comment]
Close as WNF
