### ISSUE TITLE
Not able to read pwm

### ISSUE THREAD

**Issue by Sutyke** [NVIDIA/jetson-gpio#7]
Thanks for jetson.gpio. 

Currently I'm not able to read PWM signal by Jetson nano (Jetson.GPIO) from RC receiver. PWM signal can be red by RPi but not by Jetson Nano, please find link to the code below for read_pwm on RPi:
http://abyz.me.uk/rpi/pigpio/code/read_PWM_py.zip

Is there any way Jetson.GPIO can read PWM signal as on RPi pigpio? 

Please find below the scheme for more information:
![image](https://user-images.githubusercontent.com/29728312/60471232-7384e100-9c6c-11e9-850b-7f7e0bfeeaa9.png)

**Comment by swarren** [comment]
Jetson.GPIO/RPi.GPIO do not contain any APIs to read PWM signals, no.

You would probably need to develop a Linux kernel module to read PWM signals on Jetson.
