### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by ma-ludw** [NVIDIA/jetson-gpio#71]
In this [line](https://github.com/NVIDIA/jetson-gpio/blob/7204036db1fb7f30a2b9d5e42c5b6139f13a2ca4/README.md?plain=1#L243), it is not clear if it references to the line above or below.
If it refers to the line above, it means when you set only one, the rest will be set to low. If the comment is for the line below, it means the line above the comment will set all to high and there is a typo.

**Comment by anhmiuhv** [comment]
thanks!
