### ISSUE TITLE
Problem with unofficial carrier board

### ISSUE THREAD

**Issue by XinZhenRen** [NVIDIA/jetson-gpio#75]
WARNING: Carrier board is not from a Jetson Developer Kit.
WARNNIG: Jetson.GPIO library has not been verified with this carrier board,
WARNING: and in fact is unlikely to work correctly.

**Comment by anhmiuhv** [comment]
Yes if your carrier board is not NVIDIA devkit, then there will be this message

**Comment by anhmiuhv** [comment]
Yes the library is only validated with official carrier board. For unofficial Carrier boards, the library might work or might not work. It is not validated. You can consult your carrier board manufacturer to see if the 40-pin is compatible.

Sincerely,

Linh
