### ISSUE TITLE
What does `curr_value ^= GPIO.HIGH` mean?

### ISSUE THREAD

**Issue by tsadarsh** [NVIDIA/jetson-gpio#78]
The `sample_out.py` uses:
https://github.com/NVIDIA/jetson-gpio/blob/996bb8561ef4cd4a2e6cf43b94b885d2a890f29b/samples/simple_out.py#L42

What does it do?

**Comment by anhmiuhv** [comment]
it is xor operator. it will switch the value between 1 and 0
