### ISSUE TITLE
ValueError: Channel 214 is invalid

### ISSUE THREAD

**Issue by AhmadSuper-coder** [NVIDIA/jetson-gpio#83]
import Jetson.GPIO as GPIO

#To disable the warnings
GPIO.setwarnings(False)

# Set the GPIO mode to BCM
GPIO.setmode(GPIO.BCM)

# Set pin 214 as input
GPIO.setup(214, GPIO.IN)

# Read the input status of pin 214
input_value = GPIO.input(214)

# Print the input value to the console
print("Input value of pin 214:", input_value)

# Clean up the GPIO configuration
GPIO.cleanup()

I have written this code for FC REC (Force recovery pin) but i am getting below error:

WARNING: Carrier board is not from a Jetson Developer Kit.
WARNNIG: Jetson.GPIO library has not been verified with this carrier board,
WARNING: and in fact is unlikely to work correctly.
Traceback (most recent call last):
  File "frp.py", line 7, in <module>
    GPIO.setup(214, GPIO.IN)
  File "/usr/lib/python3/dist-packages/Jetson/GPIO/gpio.py", line 358, in setup
    ch_infos = _channels_to_infos(channels, need_gpio=True)
  File "/usr/lib/python3/dist-packages/Jetson/GPIO/gpio.py", line 121, in _chans
    for c in _make_iterable(channels)]
  File "/usr/lib/python3/dist-packages/Jetson/GPIO/gpio.py", line 121, in <list>
    for c in _make_iterable(channels)]
  File "/usr/lib/python3/dist-packages/Jetson/GPIO/gpio.py", line 104, in _chanp
    raise ValueError("Channel %s is invalid" % str(channel))
ValueError: Channel 214 is invalid

  

second method i have used 

import Jetson.GPIO as GPIO

GPIO.setmode(GPIO.TEGRA_SOC)
GPIO.setup('FORCE_RECOVERY', GPIO.IN)

value = GPIO.input('FORCE_RECOVERY')
print(value)

# Clean up the GPIO configuration
GPIO.cleanup()

this is the datasheet link     : https://developer.download.nvidia.com/assets/embedded/secure/jetson/Nano/docs/JetsonNano_DataSheet_DS09366001v1.1.pdf?zypJ8Rd26hk_DVy0U_5pytz8PLl76w6LhDz1Q4SAVaU_EHeO6CQXCXZqonP8dixb26YB5bKgUWbD90BrzDF6La5YIBon93Tc7lFSo3woBmF31BXUVfpdA68HmyzUrrbCfrCOpstcREzSwQUtcCaBjbPXg84r4IJgNI-vP1MDOdqwrHhxHqrC0aa1eS2-gg==&t=eyJscyI6ImdzZW8iLCJsc2QiOiJodHRwczovL3d3dy5nb29nbGUuY29tLyIsIm5jaWQiOiJlbS1ldmVuLTM3NzQ4OCJ9

**Comment by anhmiuhv** [comment]
This lib only supports the 40 pin header. It does not support fc recovery pin
