### ISSUE TITLE
Hi Team, I am facing issue to access OpenGL for rs-capture. I am accessing Intelrealsense camera(remotely via SSH)where NVIDIA Jetson is used as graphic driver. I have updated the drivers still the issue: Could not open OpenGl please check graphic driver or use SDK textual tools. Will any one help me?

### ISSUE THREAD

**Issue by drakshayanidesai** [NVIDIA/jetson-gpio#84]
**Please don't submit questions**
Please use this form to report specific bugs in Jetson.GPIO. All general questions or support requests should be directed at NVIDIA's forums; see:
https://developer.nvidia.com/embedded/community/support-resources

Please delete this section from your bug report.

**Describe the bug**
A clear and concise description of what the bug is, including
- Which version of Jetson.GPIO you are using.
- Which version of L4T (not JetPack) you are using.
- Which Jetson board you are using.

**To Reproduce**
1. Connect  button/wire/LED/... XXX to the board
2. Configure pin ... to input/output/...
3. Execute API ...

**Expected behavior**

**Additional context**

**Comment by anhmiuhv** [comment]
This is not related to Jetson.GPIO
