### ISSUE TITLE
Jetson orin nano pin 32 "Channel 32 is not a PWM"

### ISSUE THREAD

**Issue by ARK3r** [NVIDIA/jetson-gpio#91]
Using the `samples/simple_pwm.py` on the Orin Nano and changing the pin from 33 to 32 (which both are valid pwm pins from `/opt/nvidia/jetson-io/jetson-io.py`) results in the error that channel 32 is not a PWM.

I was hoping support for both PWMs could be provided.

**Comment by anhmiuhv** [comment]
This is fixed in the latest version
