### ISSUE TITLE
Docker container can't be run as non-privileged with mapped dev volume 

### ISSUE THREAD

**Issue by Levaru** [NVIDIA/jetson-gpio#96]
I'm using the latest version of Jetson.GPIO (commit 4e4f615).

I followed the instructions in the README and tried to run my docker container as non-privileged. This fails because it's not able to access `_GPIOCHIP_ROOT = "/dev/gpiochip0"` in `gpio.py` in this [line](https://github.com/NVIDIA/jetson-gpio/blob/4e4f615c6429a57dba8452cfca558e5768a138f3/lib/python/Jetson/GPIO/gpio.py#L32).

If I run it with the `--privileged` flag it works as expected.

After some research, it looks like the correct flag to use would be `--device` to map `gpiochip0` instead of mapping all devices with `-v /dev:/dev`. 

So I believe the correct full command to run the docker container as non-privileged should look like this:
```
sudo docker container run -it --rm \
--runtime=nvidia --gpus all \
--device /dev/gpiochip0 \
-e JETSON_MODEL_NAME=[PUT_YOUR_JETSON_MODEL_NAME_HERE] \
testimg /bin/bash
```

**Comment by anhmiuhv** [comment]
Thanh you for raising this error. I will post a fix
