### ISSUE TITLE
warn_if_not_carrier_board error check

### ISSUE THREAD

**Issue by Wu-Fisher** [NVIDIA/jetson-gpio#99]
I am using the Jetson Orin NX developer kit-16GB. 
When I imported jetson.gpio, the terminal showed message of
"WARNING: Carrier board is not from a Jetson Developer Kit.
WARNNIG: Jetson.GPIO library has not been verified with this carrier board,
WARNING: and in fact is unlikely to work correctly."
So I went to check the source code. I got "
        elif matches(compats_jetson_orins_nx):
            warn_if_not_carrier_board('3509', '3768')
            return JETSON_ORIN_NX" in "gpio_pin_data.py:585"
That would check the file "/proc/device-tree/chosen/ids" to see if 3768 is the prefix.
But my own file is only 3767.
I am a green hand of such devices, so there might be some error description.

**Comment by anhmiuhv** [comment]
3767 is the module not the carrier board. Is your target official NVIDIA Jetson Orin NX? 

You could also this repo anyway to see if it works or not if it is official NVIDIA Jetson Orin NX.

**Comment by Wu-Fisher** [comment]
> 3767 is the module not the carrier board. Is your target official NVIDIA Jetson Orin 
<img width="464" alt="image" src="https://github.com/NVIDIA/jetson-gpio/assets/73976255/3abc0857-0cb3-43d6-9418-b920c1d42c08">

It should be official.right?

**Comment by anhmiuhv** [comment]
Yeah you can try to ignore the warning and run it

**Comment by Wu-Fisher** [comment]
yep, that is what I had done.

**Comment by anhmiuhv** [comment]
If you have no more problem I will close this.
